# Generated by Django 3.2.8 on 2021-10-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blogpost_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='sebanzian', max_length=16),
            preserve_default=False,
        ),
    ]
