# Generated by Django 3.2.8 on 2021-10-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='teaser',
            field=models.CharField(default='Here could be your teaser text', max_length=150),
            preserve_default=False,
        ),
    ]
